version: 0.1
env:
  variables:
    APP_ENV: 'prod'
artifacts:
  #  get files within the dist folder only
  base-directory: '*'
  discard-paths: yes
  files:
    - index.html
    - stylesheet.css
    - error.html